apiVersion: v1
kind: Service
metadata:
 name: ssh
 annotations:
   service.kubernetes.io/ibm-load-balancer-cloud-provider-enable-features: "nlb"
   service.kubernetes.io/ibm-load-balancer-cloud-provider-ip-type: public
   service.kubernetes.io/ibm-load-balancer-cloud-provider-vpc-node-selector: "app=ssh"
spec:
 type: LoadBalancer
 selector:
   app: ssh
 ports:
    -   port: 22 
        protocol: TCP
        name: ssh 
        targetPort: 22
 externalTrafficPolicy: Local
